### ISSUE TITLE
New 3DS XL

### ISSUE THREAD

**Issue by ghost** [sebascontre/bootscreen3ds#2]
When choosing N3DSXL it also displays that the DS is red, would like to see availability for other colors.

**Comment by sebascontre** [comment]
Look in the back of your New 3DS XL, RED-001 is the codename of the model for all N3DSXL, not the color. Yeah, is weird, but Nintendo made that.

3DS -> CTR  |  3DSXL -> SPR  |  2DS -> FTR  |  N3DS -> KTR  |  N3DSXL -> RED

**Comment by ghost** [comment]
ah okay, thanks for the info!
