### ISSUE TITLE
No SD card

### ISSUE THREAD

**Issue by Pitel** [sebascontre/bootscreen3ds#4]
Please add support for no SD card. So that we can put it on CTR partition to show without SD card.

**Comment by qimiko** [comment]
It's a simple thing, really.

Add this line to the SD card option:

`<option value ="No">None</option>`

It'll look like this in the end:

```html
<select name="sd" class="form-control">
	<option value ="No">None</option>
	<option value="2G" selected="selected">2GB</option>
	<option value="4G">4GB</option>
	<option value="8G">8GB</option>
	<option value="16G">16GB</option>
	<option value="32G">32GB</option>
	<option value="64G">64GB</option>
	<option value="128G">128GB</option>
	<option value="200G">200GB</option>
	<option value="256G">256GB</option>
</select>
```

If I felt like it, I could make it a bit more complex with some Javascript, but it should be good for what you want. :)
